[package]
name = "liorian-socle"
version = "0.13.0"
description = "Liorian Manager desktop/mobile application"
authors = ["Liorian"]
edition = "2021"

[lib]
name = "liorian_socle_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-notification = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
